/**
 * Default categories seeded on first plugin load when categories.json is missing or empty.
 * Devs can evolve the list via add_categories / remove_categories tools.
 */
export const SEED_CATEGORIES: string[] = [
  "Ancient Civilizations",
  "Animal Kingdom",
  "Architecture",
  "Art History",
  "Astronomy",
  "Board Games",
  "Botany",
  "Chemistry",
  "Cinema",
  "Classical Music",
  "Climate & Weather",
  "Cooking & Cuisine",
  "Cryptography",
  "Dance",
  "Economics",
  "Engineering",
  "Fashion",
  "Folklore & Myths",
  "Geography",
  "Geology",
  "Human Body",
  "Insects",
  "Inventions",
  "Jazz & Blues",
  "Languages",
  "Literature",
  "Marine Biology",
  "Mathematics",
  "Medieval History",
  "Microbiology",
  "Modern History",
  "Motorsports",
  "Mythology",
  "Oceanography",
  "Olympics",
  "Paleontology",
  "Philosophy",
  "Photography",
  "Physics",
  "Pop Culture",
  "Psychology",
  "Space Exploration",
  "Sports Records",
  "Technology",
  "Television",
  "Theater",
  "Urban Legends",
  "Video Games",
  "Volcanoes",
  "World Records",
];
